[[constraint]]
  branch = "master"
  name = "github.com/pulumi/pulumi"

[[constraint]]
  version = "v0.11.11"
  name = "github.com/hashicorp/terraform"

  [constraint.metadata]
    govendor-override = true
    govendor-exclude-prefixes = [
      "github.com/coreos/etcd",
      "google.golang.org/grpc",
      "github.com/golang/protobuf",
      "github.com/mattn/go-isatty",
    ]
